---
title: "Study 1"
author: "Joel Larwood"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---
# Study 1 Analysis 

## Set up and load data 
```{r setup, message = FALSE}
library(tidyverse)
library(interactions)
library(sjPlot)
library(psych)
library(knitr)
library(kableExtra)
library(lmerTest)
library(expss)
```

```{r import data, message=FALSE, warning=FALSE}
study1 <- read_csv("RMER_Study1.csv") %>% select(id,
                                                 Age,
                                                 Gender,
                                                 Sample,
                                                 Condition,
                                                 contains("POMS"),
                                                 contains("RRQ"),
                                                 contains("self"),
                                                 contains("pop"),
                                                 contains("ness"),
                                                 valence,
                                                 mode,
                                                 energy,
                                                 tempo,
                                                 key,
                                                 danceability,
                                                 contains("music"))
names(study1)

```


## Create Scores 
```{r create scores}
study1 <- study1 %>% mutate(Baseline = rowSums(select(., POMSDSF1_1:POMSDSF8_1)),
                            Post_induction = rowSums(select(., POMSDSF1_2:POMSDSF8_2)),
                            Post_listening = rowSums(select(., POMSDSF1_3:POMSDSF8_3)),
                            Rumination = (RRQ1_1 + RRQ2_1 + RRQ3_1 + RRQ4_1 + RRQ5_1 + (6 - RRQ6_1) + RRQ7_1 + RRQ8_1 + (6 - RRQ9_1) + (6 - RRQ10_1) +RRQ11_1 + RRQ12_1)/12)
names(study1)
describe(select(study1, 
                Baseline,
                contains("Post"),
                Rumination)) %>% select(-vars,
                                        -trimmed,
                                        -mad,
                                        -range) %>% round(digits = 3)
```
## Create Long data 
```{r long data}
S1long <- gather(data = study1,
                 key = Timepoint,
                 value = Sadness,
                 Baseline, Post_induction, Post_listening) %>% select(-contains("POMS"), -contains("RRQ"))


S1long <- S1long %>% mutate(Timepoint = as.factor(.$Timepoint),
                            id = as.factor(.$id),
                            Condition = as.factor(.$Condition))

write_csv(S1long, "RMER_Study1_long.csv")
```



## Test Hypothesis 
### Set up models
```{r set up models}
timecondint <- lmer(Sadness~1+Timepoint*Condition+(1|id), data = S1long)
timecondintrum <- update(timecondint, .~. + Rumination)
all <- update(timecondintrum, .~. +Timepoint*Condition*Rumination)


anova(timecondint, timecondintrum, all)

tab_model(timecondint, timecondintrum, all)
anova(timecondintrum)
```

```{r manipulation}
lmerTest::difflsmeans(timecondintrum, which = "Timepoint") %>% round(3)
```

```{r simple slopes}
lmerTest::ls_means(timecondintrum, pairwise = TRUE) %>% kable()
```

## Plot
```{r, warning = FALSE, message=FALSE}
interactions::cat_plot(model = timecondintrum,
                       pred = Timepoint,
                       modx = Condition,
                       interval = TRUE,
                       geom = "line",
                       line.thickness = .5,
                       point.size = .75) + theme_classic() + scale_x_discrete(labels = c("Baseline", "Post Induction", "Post Listening"))
```


