---
title: "RMER_November2018_MusicExplore"
author: "joellarwood"
date: "2019-12-17"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction


```{r echo = FALSE, warnings = FALSE, message=FALSE}
library(tidyverse)
library(lmerTest)
library(emmeans)
library(sjPlot)
library(apa)
library(interactions)
library(tidytext)
library(glue)
library(Hmisc)

knitr::opts_chunk$set(autodep = TRUE, warnings = FALSE, message = FALSE)

options(scipen=999, digits=3)
```


```{r LoadIn}

Nov18Features_Lyrics <- read_rds(here::here("data", "RMER_November2018_Spotify_Lyrics.rds")) 
Nov18Features <- read_rds(here::here("data", "RMER_November2018_Spotify.rds"))
```


```{r BRECVEMA}


mech <- Nov18Features %>% select(BSR:Appraisal) %>% names() 

BRECVEMA_Chi2 <- Nov18Features %>% 
  drop_na() %>% 
  select(mech) %>% 
  map( ~ .x-1) %>% 
  as_tibble()


for (i in 1:8) {
  table <- table(BRECVEMA_Chi2[,i]) 
  chi <- chisq.test(table)
  stat <- round(chi[["statistic"]][["X-squared"]], 2)
  p <- round(chi[["p.value"]], 3)
  name <- colnames(BRECVEMA_Chi2[, i])
  df <- chi[["parameter"]][["df"]]
  count <- data.frame(table)
  yes <- (count)[1,2]
  no <- (count)[2,2]
  result <- glue::glue("The statistic for {name} was X^2({df}){stat}, p = {p}. {yes} responded yes 
                       and {no} responded no")
  print(result)
}

```

BRECVEMA Correlations 
```{r}

Nov18Features %>% 
  select(rumination, musebaq, mech) %>% 
  apaTables::apa.cor.table(filename = here::here("docs", "Nov18_BECVEMACor.rtf"))

```

Here we can see that people higher in rumination were more likely to experience Conditioning, contagion and memories

Here is an exploration of how they relate to changes in sadness 

```{r}
Nov18LongBRECVEMA <- Nov18BasicClean  %>% 
  select(ResponseId, 
         Baseline:rumination, 
         hours.listen,
         mech,
         musebaq) %>% 
  pivot_longer(cols = PostInduction:PostListening, 
               names_to = "Timepoint", 
               names_ptypes = factor(), 
               values_to = "Sadness") %>% 
  map_at(.at = vars(mech), 
         .f = as_factor) %>% 
  map_at(.at = vars(mech), 
         .f = fct_recode, 
         "Yes" = "0", 
         "No" = "1") %>% 
  map_at(.at = vars(mech), 
         .f = fct_relevel, "No") %>% 
  as_tibble() 

write_rds(Nov18LongBRECVEMA, 
          here::here("data", "Nov18LongExplore.rds"))
  

Hypothesised <- lmerTest::lmer(Sadness~ 1+Timepoint*rumination +  (1 | ResponseId), data = drop_na(Nov18LongBRECVEMA))

traits <- lmerTest::lmer(Sadness~ 1+Timepoint*rumination + Timepoint*Baseline + Timepoint*musebaq+ (1 | ResponseId), data = drop_na(Nov18LongBRECVEMA))

BRECVEMA <- lmerTest::lmer(Sadness~ 1+Timepoint*rumination + Timepoint*Conditioning + Timepoint*Memory + Timepoint*Contagion+ Timepoint*BSR+(1 | ResponseId), data = drop_na(Nov18LongBRECVEMA))

BRECVEMAtraits <- lmerTest::lmer(Sadness~ 1+Timepoint*rumination + Timepoint*Baseline + Timepoint*musebaq+ Timepoint*Contagion + Timepoint*Conditioning + Timepoint*Memory +Timepoint*BSR+ (1 | ResponseId), data = drop_na(Nov18LongBRECVEMA))

anova(Hypothesised, traits, BRECVEMA) %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling()

anova(Hypothesised, BRECVEMA)

anova(BRECVEMA, traits)

anova(BRECVEMAtraits, traits, BRECVEMA)

tab_model(BRECVEMAtraits, 
          show.std = TRUE, 
          show.aic = TRUE)

```

# Fully exploratory model 

```{r}
FullExploreSyntax <- Sadness~ 1+Timepoint*rumination + Timepoint*Baseline + Timepoint*musebaq+ Timepoint*BSR + Timepoint*Entrainment + Timepoint*Contagion +Timepoint*Imagery+ Timepoint*Memory+Timepoint*Expectancy+Timepoint*Appraisal+ (1 | ResponseId)

ExploratoryModel <- buildmer::buildmer(FullExploreSyntax,
                        data=drop_na(Nov18LongBRECVEMA),
                        direction='backward',
                        control=lmerControl(optimizer='bobyqa'))

ExploratoryModelForceRum <- buildmer::buildmer(FullExploreSyntax,
                                       include = ~ Timepoint*rumination,
                        data=drop_na(Nov18LongBRECVEMA),
                        direction='backward',
                        control=lmerControl(optimizer='bobyqa'))

anova(ExploratoryModelForceRum@model, ExploratoryModel@model)

tab_model(ExploratoryModelForceRum@model, ExploratoryModel@model)

ExploreExtractPlusRum <- lmer(formula = Sadness ~ 1 + Timepoint + 
    Baseline + musebaq + BSR + Timepoint:BSR + Contagion + Timepoint:Contagion +
    Memory + Timepoint:Memory + Appraisal + Timepoint:Appraisal + Timepoint*rumination + 
    (1 | ResponseId), data = drop_na(Nov18LongBRECVEMA))

anova(Hypothesised, ExploreExtract, ExploreExtractPlusRum)

tab_model(ExploreExtractPlusRum)
```




```{r ProcessLyricSent}
## Processing of lyrics taken from https://www.rcharlie.com/post/fitter-happier/

sad_words <- tidytext::get_sentiments("nrc") %>% 
  filter(sentiment == "sadness") %>% 
  select(word) %>% 
  mutate(sad = T)

pos_words <- tidytext::get_sentiments("nrc") %>% 
  filter(sentiment == "positive") %>% 
  select(word) %>% 
  mutate(positive = T)

neg_words <- tidytext::get_sentiments("nrc") %>% 
  filter(sentiment == "negative") %>% 
  select(word) %>% 
  mutate(negative = T)

Nov18_Sent <- Nov18Features_Lyrics %>% 
  unnest_tokens(word, lyric) %>%
  select(word, song_artist) %>% 
  anti_join(stop_words, by = 'word') %>%
  left_join(sad_words, by = 'word') %>% # can add to pipe to add postive, angry, words etc by creating a new data frame that just has those words (i.e. get_sentiments("nrc") %>% filter(sentiments == "sentiment") %>%  ... )
  left_join(pos_words, by = "word") %>% 
  left_join(neg_words, by = "word")  %>%  
  group_by(song_artist) %>% 
  summarise(word_count = n(),
            sad_count = sum(sad, na.rm = T), 
            pos_count = sum(positive, na.rm = T), 
            neg_count = sum(negative, na.rm = TRUE), 
            sad_total_ratio = round(exp(sad_count)/ exp(word_count), 4),
            neg_pos_ratio = round(exp(neg_count)/exp(pos_count), 4), 
            sad_pos_ratio = round(exp(sad_count)/exp(pos_count), 4)) %>% 
  mutate(bias = if_else(neg_pos_ratio > 1, 
                        "Negative", 
                        if_else (neg_pos_ratio< 1,
                                 "Positive",
                                 if_else(neg_pos_ratio == 1, 
                                         "Equal", "NA")))) 

Nov18_Features_Sent <- Nov18_Sent %>% 
  right_join(Nov18Features, by = "song_artist") 

```

#Look at distributions of key variables with rumination 
## Spotify data 
```{r}

Nov18_Features_Sent %>% 
  select(rumination, musebaq, valence, energy) %>% 
  drop_na() %>% 
  as.matrix() %>% 
  Hmisc::rcorr(type = "spearman")
  
```

## Spotify and lyric data 
```{r}
Nov18_Features_Sent %>% 
  select(rumination, musebaq, valence, energy, contains("_ratio")) %>% 
  drop_na() %>% 
  as.matrix() %>% 
  Hmisc::rcorr(type = "spearman")
```

